<?php
$title = $this->translate('Sign Up');
#meta keywords
$this->headMeta()->appendName('keywords','Sign Up, Create,Join,New Account');
#meta description
$this->headMeta()->appendName('description','Create a new Account');
# page title
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
// var_dump($form);
// $form->setAttribute('action', $this->url('signup'));
$form->prepare();
?>
<div class="container">
	
	<div class="row">
		<div class="col-md-8 shadow-sm offset-2 mb-5 mt-5">
		<h3 class="mb-3 pt-2 text-md-center">
			<?= $this->escapeHtml($this->translate('Create a New Account'));  ?>
		</h3>
		<?= $this->form()->openTag($form);  ?>
		<span class="form-text text-muted pb-2">
			<?= sprintf($this->translate('Already have an Account? %sLogin here%s.'),
		 '<a href="/login">', '</a>'
		); ?>
		</span>
	
		<div class="mb-3">
			<?= 
			$this->formLabel($form->get('first_name'));?>
			<div class="form-group">
				<?= $this->formText($form->get('first_name')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('first_name')); ?>
			</div>
		</div>

		<!-- last name -->
		<div class="mb-3">
			<?= $this->formLabel($form->get('last_name'));   ?>
			<div class="form-group">
				<?= $this->formText($form->get('last_name')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('last_name')); ?>
			</div>
		</div>

		<!-- last name -->
		<div class="mb-3">
			<?= $this->formLabel($form->get('gender'));   ?>
			<div class="form-group">
				<?= $this->formSelect($form->get('gender')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('gender')); ?>
			</div>
		</div>

			<!-- Add the username input field -->
		<div class="mb-3">
			<?= $this->formLabel($form->get('username'));   ?>
			<div class="form-group">
				<?= $this->formText($form->get('username')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('username')); ?>
			</div>
		</div>

		<!-- Email Address input filed -->
		<div class="mb-3">
			<?= $this->formLabel($form->get('email'));   ?>
			<div class="form-group">
				<?= $this->formEmail($form->get('email')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('email')); ?>
			</div>
		</div>

		
		<!-- confirm email Address input filed -->
		<div class="mb-3">
			<?= $this->formLabel($form->get('confirm_email'));   ?>
			<div class="form-group">
				<?= $this->formEmail($form->get('confirm_email')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('confirm_email')); ?>
			</div>
		</div>

		<!--Password field -->
		<div class="mb-3">
			<?= $this->formLabel($form->get('password'));   ?>
			<div class="form-group">
				<?= $this->formPassword($form->get('password')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('password')); ?>
			</div>
		</div>

		<!-- confirm password -->

		<div class="mb-3">
			<?= $this->formLabel($form->get('confirm_password'));   ?>
			<div class="form-group">
				<?= $this->formPassword($form->get('confirm_password')); ?>
			</div>
			<div class="text-danger">
				<?= $this->formElementErrors($form->get('confirm_password')); ?>
			</div>
		</div>

		
		<!-- submit and csrf field -->
			<!-- Add the username input field -->
		<div class="mb-3">
	
			
				<?= $this->formSubmit($form->get('create_account')); ?>
		<!-- close the form -->
		<?= $this->form()->closeTag();   ?> 
			
		</div>
	</div>
	</div>
</div>