<?php
$title = "Users";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
<a href="<?= $this->url('admin', ['action' => 'add']) ?>">Add new User</a>	
</p>
<table class="table">
	<tr>
		<th>User ID</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>User Name</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Time</th>
		<th>Actions</th>
	</tr>
	 <?php foreach ($users as $user) : ?>
		<tr>
			<td><?= $this->escapeHtml($user->user_id) ?></td>
			<td><?= $this->escapeHtml($user->first_name) ?></td>
			<td><?= $this->escapeHtml($user->last_name) ?></td>
			<td><?= $this->escapeHtml($user->username) ?></td>
			<td><?= $this->escapeHtml($user->email) ?></td>
			<td><?= $this->escapeHtml($user->gender) ?></td>
			<td><?= $this->escapeHtml($user->created_at) ?></td>
			<td>
				<a class="btn btn-primary" href="<?= $this->url('admin',['action'=>'Edit','id'=> $user->user_id]) ?>">Edit</a>
				<a class="btn btn-danger"  href="<?= $this->url('admin',['action'=>'Delete','id'=> $user->user_id]) ?>">Delete</a>
			</td>
		</tr>
	<?php endforeach ?>
</table>