<?php

$title = "Create New Enrollment";
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title)  ?></h1>

<?php

$course_id = $form->get('course_id');
$course_id->setAttribute('class','form-control');

$user_id = $form->get('user_id');
$user_id->setAttribute('class','form-control');

$submit = $form->get('enroll');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('enrollment', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form); 
?>

<div class="form-group">
	<?= $this->formLabel($course_id)  ?>
	<?= $this->formElement($course_id)  ?>
	<?= $this->formElementErrors()->render($course_id,['class' => 'help-block'])  ?>
</div>

<div class="form-group">
	<?= $this->formLabel($user_id)  ?>
	<?= $this->formElement($user_id)  ?>
	<?= $this->formElementErrors()->render($user_id,['class' => 'help-block'])  ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
